### ISSUE TITLE
show-remove-button show at right bottom, but it should at right top

### ISSUE THREAD

**Issue by rocket1024** [zhanziyang/vue-croppa#105]
when enable remove button, it should be showing at right top,
use webpack
in file upload.vue

<template>
<div>
<croppa v-model="myCroppa" 
...

**Comment by zhanziyang** [comment]
Please provide a reproducible demo.

**Comment by zhanziyang** [comment]
What is the purpose of using flexbox layout on `.croppa-container`. It's not a good practice.

**Comment by rocket1024** [comment]
but the default button position is bottom right, which is not desired, I use the webpack, which the src code upload.vue, seems might be affect the button style

**Comment by zhanziyang** [comment]
The default position is top right. If you want to change it, you can modify the css properties for `.croppa-container svg.icon-remove`

For example, if you want to set the button to top left, just write:
```css
.croppa-container svg.icon-remove {
    top: 0 !important;
    right: unset !important;
    left: 0 !important;
}
```
