### ISSUE TITLE
Border radius on canvas / image preview?

### ISSUE THREAD

**Issue by sejr** [zhanziyang/vue-croppa#108]
I am trying to show a preview to users with a circular photo, but I want to store the regular square original. I essentially just want a border radius on the canvas but it doesn't seem to be working. Is there a specific CSS selector I should be targeting?

**Comment by zhanziyang** [comment]
You should set it on `.croppa-container`.

```css
.croppa-container {
  border-radius: 50%;
}
```
