### ISSUE TITLE
Placeholder image does not fill container

### ISSUE THREAD

**Issue by TheAustinG** [zhanziyang/vue-croppa#161]
When I set a height and width for the component/container, the placeholder image still has a static height/width of 200px.

```html
<croppa class="c1" v-model="assetImage">
     <img slot="placeholder" src="https://placehold.it/500x500" />
</croppa>
```

```css
<style>
     .croppa-container.c1 {
         width: 100%;
         height: 350px;
     }
</style>
```

![image](https://user-images.githubusercontent.com/14006557/51408714-511b6300-1b25-11e9-914f-204c1d658a3e.png)
